stages:
  - build
  - test
  - release

variables:
  IMAGE_NAME: "registry.gitlab.com/devsecops-hub/gitlab-devsecops-pipeline"

build_image:
  stage: build
  when: manual
  image: docker:24.0
  script:
    - apk add --no-cache make
    - make
    - |
      echo "Building DevSecOps tools image..."
      make build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - docker/**/*

test_image:
  stage: test
  image: "$IMAGE_NAME:$CI_COMMIT_SHA"
  script:
    - echo "Testing installed tools..."
    - yq --version
    - gitleaks version
    - semgrep --version
    - dependency-check --version
    - echo "All tools are working correctly"
  needs:
    - build_image

release_image:
  stage: release
  when: manual
  image: docker:24.0
  script:
    - docker tag "$IMAGE_NAME:$CI_COMMIT_SHA" "$IMAGE_NAME:$CI_COMMIT_TAG"
    - docker push "$IMAGE_NAME:$CI_COMMIT_TAG"
    - echo "Released image $IMAGE_NAME:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - test_image
