stages:
  - build
  - test
  - release

variables:
  IMAGE_NAME: "$DOCKERHUB_USER/devsecops-tools"

docker_login:
  stage: .pre
  image: docker:24.0
  services:
    - docker:24.0-dind
  before_script:
    - echo "Logging in to Docker Hub..."
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
  script:
    - echo "Docker login successful"
  rules:
    - if: $DOCKERHUB_USER && $DOCKERHUB_PASSWORD

build_image:
  extends: docker_login
  stage: build
  when: manual
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - |
      echo "Building DevSecOps tools image..."
      cd docker
      docker build \
        --build-arg YQ_VERSION=v4.40.5 \
        --build-arg GITLEAKS_VERSION=8.21.2 \
        --build-arg DEPENDENCY_CHECK_VERSION=9.0.8 \
        --tag "$IMAGE_NAME:$CI_COMMIT_SHA" \
        --tag "$IMAGE_NAME:latest" \
        .
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - docker/**/*

test_image:
  stage: test
  image: "$IMAGE_NAME:$CI_COMMIT_SHA"
  script:
    - echo "Testing installed tools..."
    - yq --version
    - gitleaks version
    - semgrep --version
    - dependency-check --version
    - echo "All tools are working correctly"
  needs:
    - build_image

release_image:
  extends: docker_login
  stage: release
  when: manual
  image: docker:24.0
  services:
    - docker:24.0-dind
  script:
    - docker tag "$IMAGE_NAME:$CI_COMMIT_SHA" "$IMAGE_NAME:$CI_COMMIT_TAG"
    - docker push "$IMAGE_NAME:$CI_COMMIT_TAG"
    - echo "Released image $IMAGE_NAME:$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - test_image
