stages:
  - build
  - test
  - release

variables:
  LOCAL_IMAGE_BASE: "devsecops-tools"
  IMAGE_FULL_PATH: "registry.gitlab.com/devsecops-hub/gitlab-devsecops-pipeline"

build_image:
  stage: build
  when: manual
  image: docker:24.0
  services:
    - docker:24.0-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
    CI_REGISTRY_IMAGE: "$IMAGE_FULL_PATH"
    CI_COMMIT_SHA: "$CI_COMMIT_SHA"
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USER" --password-stdin
    - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - apk add --no-cache make
    - make
    - |
      echo "Building DevSecOps tools image..."
      make build
    - docker push "$IMAGE_FULL_PATH:$CI_COMMIT_SHA"
    - docker push "$IMAGE_FULL_PATH:latest"
    - echo "Image built and pushed successfully"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - docker/**/*
